[book]
authors = ["Tim Janus"]
language = "en"
multilingual = false
src = "book_src"
title = "ğŸ¦€ Rust ğŸ¦€ - Procedural Macros - Expand and Implement! ğŸ¦€"

[output.html.playground]
runnable = true

[output.html.print]
enable = true

[output.pdf]
