[package]
name = "e_mypoint_custom_derive_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["extra-traits"] }
quote = { version = "1.0" }
proc-macro2 = { version = "1.0" }

[lib]
proc-macro = true
