[package]
name = "e_mypoint_custom_derive_greetings"
version = "0.1.0"
edition = "2024"

[dependencies]
e_mypoint_custom_derive_macros = { path = "../e_mypoint_custom_derive_macros", version = "0.1" }